version: 2
jobs: 
  build:
    machine: true
    working_directory: ~/drill_sergeant
    steps:
      - checkout
      - run: docker-compose up -d
      - run: docker run -e CI=true drill_sergeant_client yarn test
      - run: docker run --rm drill_sergeant_api bundle exec rake
      - run: docker build -t beeberino/drill_sergeant-client ./client
      - run: docker build -t beeberino/drill_sergeant-proxy ./nginx
      - run: docker build -t beeberino/drill_sergeant-server ./server
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
      - run: docker push beeberino/drill_sergeant-client
      - run: docker push beeberino/drill_sergeant-proxy
      - run: docker push beeberino/drill_sergeant-server