version: 2
jobs: 
  build:
    machine: true
    working_directory: ~/drill-sergeant
    steps:
      - checkout
      - run: docker-compose up -d
      - run: docker-compose run -e CI=true client yarn test
      - run: docker-compose run --rm api bundle exec rake
      - run: docker build -t beeberino/drill-sergeant-client ./client
      - run: docker build -t beeberino/drill-sergeant-proxy ./nginx
      - run: docker build -t beeberino/drill-sergeant-server ./server
      - run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
      - run: docker push beeberino/drill-sergeant-client
      - run: docker push beeberino/drill-sergeant-proxy
      - run: docker push beeberino/drill-sergeant-server